id: I6ACF8FC1
legacy_id: P003175
ocr_import_info:
  bdrc_scan_id: W861
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T01:40:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:19:54.698979+00:00'
last_modified: 2022-09-04 11:21:16.132184
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W861
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW861
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་འདུན་རྒྱ་མཚོ། ༼དཀར་མཛེས་པར་མ།༽
  author: ཏཱ་ལའི་བླ་མ ༠༢་དགེ་འདུན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5257897656232549
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1KG11687:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11687
      total_pages: 1048
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG11687.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5300017726353602
    legacy_id: v002
  I1KG11686:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11686
      total_pages: 980
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11686.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5235101944516196
    legacy_id: v001
  I1KG11688:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11688
      total_pages: 874
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG11688.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5242067975184329
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
