id: I6ACF8FC1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:46:53+00:00'
last_modified: '2022-06-07T18:05:45.924919+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W861
  title: གསུང་འབུམ། དགེ་འདུན་རྒྱ་མཚོ། ༼དཀར་མཛེས་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '9596':
      image_group_id: I1KG11686
      title: ''
      total_pages: 980
      order: 1
      base_file: 9596.txt
    67C7:
      image_group_id: I1KG11687
      title: ''
      total_pages: 1048
      order: 2
      base_file: 67C7.txt
    6B46:
      image_group_id: I1KG11688
      title: ''
      total_pages: 874
      order: 3
      base_file: 6B46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
